title: My Blog
description: A place to share thoughts and experiences
theme: minima
plugins:
  - jekyll-feed
author:
  name: Milad Vazan
  email: mail@miladai.ir
  display_in_footer: true  # Control author display in footer

