title: Milad Vazan's Blog
email: your-email@example.com
description: >- 
  A simple blog by Milad Vazan
baseurl: "" 
url: "https://miladvazan.github.io" 
twitter_username: miladvazan
github_username:  miladvazan

theme: minima
plugins:
  - jekyll-feed
